#pragma once

#define LV_COLOR_DEPTH 16
#define LV_USE_OS LV_OS_FREERTOS
#define LV_MEM_CUSTOM 0
#define LV_USE_LOG 1
#define LV_LOG_LEVEL LV_LOG_LEVEL_WARN
#define LV_USE_ASSERT_NULL 1
#define LV_USE_ASSERT_MALLOC 1
#define LV_USE_ASSERT_STYLE 0